<?php
require __DIR__.'/auth.php'; require_login(); header('Content-Type: application/json; charset=utf-8');
$db=new SQLite3(__DIR__.'/DATABASE/notes.db'); $db->exec('CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL DEFAULT \'Ghi chú mới\',content TEXT NOT NULL DEFAULT \'\',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)');
$cols=[];$r=$db->query('PRAGMA table_info(notes)');while($c=$r->fetchArray(SQLITE3_ASSOC))$cols[]=$c['name'];
if(!in_array('title',$cols,true)){ $db->exec('ALTER TABLE notes RENAME TO notes_legacy');$db->exec('CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL DEFAULT \'Ghi chú cũ\',content TEXT NOT NULL DEFAULT \'\',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)');$db->exec("INSERT INTO notes(user_id,content,created_at,updated_at) SELECT user_id,content,datetime('now','localtime'),COALESCE(updated_at,datetime('now','localtime')) FROM notes_legacy"); }
$uid=(int)$_SESSION['user_id'];function out($x,$s=200){http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE);exit;}
if($_SERVER['REQUEST_METHOD']==='GET'){if(isset($_GET['id'])){$q=$db->prepare('SELECT * FROM notes WHERE id=:id AND user_id=:u');$q->bindValue(':id',(int)$_GET['id'],SQLITE3_INTEGER);$q->bindValue(':u',$uid,SQLITE3_INTEGER);$x=$q->execute()->fetchArray(SQLITE3_ASSOC);if(!$x)out(['error'=>'Không tìm thấy ghi chú'],404);out($x);} $q=$db->prepare('SELECT id,title,substr(content,1,180) preview,created_at,updated_at FROM notes WHERE user_id=:u ORDER BY updated_at DESC');$q->bindValue(':u',$uid,SQLITE3_INTEGER);$r=$q->execute();$items=[];while($x=$r->fetchArray(SQLITE3_ASSOC))$items[]=$x;out($items);}
if($_SERVER['REQUEST_METHOD']==='POST'){$b=json_decode(file_get_contents('php://input'),true)?:[];$title=trim((string)($b['title']??'Ghi chú mới'));$content=(string)($b['content']??'');$id=(int)($b['id']??0);if($title==='')$title='Ghi chú mới';if(strlen($title)>120||strlen($content)>10000)out(['error'=>'Tiêu đề tối đa 120 và nội dung tối đa 10.000 ký tự'],422);if($id){$q=$db->prepare("UPDATE notes SET title=:t,content=:c,updated_at=datetime('now','localtime') WHERE id=:id AND user_id=:u");$q->bindValue(':id',$id,SQLITE3_INTEGER);}else{$q=$db->prepare("INSERT INTO notes(user_id,title,content,created_at,updated_at) VALUES(:u,:t,:c,datetime('now','localtime'),datetime('now','localtime'))");}$q->bindValue(':u',$uid,SQLITE3_INTEGER);$q->bindValue(':t',$title,SQLITE3_TEXT);$q->bindValue(':c',$content,SQLITE3_TEXT);$q->execute();out(['ok'=>true,'id'=>$id?:$db->lastInsertRowID()]);}
if($_SERVER['REQUEST_METHOD']==='DELETE'){parse_str(file_get_contents('php://input'),$b);$q=$db->prepare('DELETE FROM notes WHERE id=:id AND user_id=:u');$q->bindValue(':id',(int)($b['id']??0),SQLITE3_INTEGER);$q->bindValue(':u',$uid,SQLITE3_INTEGER);$q->execute();out(['ok'=>true]);}out(['error'=>'Method not allowed'],405);
